TABLE_NAME = "filesystem_entries"
SCHEMA_VERSION = 7

COLUMN_DEFINITIONS = [
    ("id", "INTEGER PRIMARY KEY"),
    ("scan_id", "TEXT NOT NULL"),
    ("scanner_version", "TEXT NOT NULL"),
    ("scanned_at_ns", "INTEGER NOT NULL"),
    ("scan_root_display", "TEXT NOT NULL"),
    ("scan_root_b64", "TEXT NOT NULL"),
    ("relative_path_display", "TEXT NOT NULL"),
    ("relative_path_b64", "TEXT NOT NULL"),
    ("relative_path_hex", "TEXT NOT NULL"),
    ("parent_path_display", "TEXT NOT NULL"),
    ("parent_path_b64", "TEXT NOT NULL"),
    ("name_display", "TEXT NOT NULL"),
    ("name_b64", "TEXT NOT NULL"),
    ("name_hex", "TEXT NOT NULL"),
    ("path_depth", "INTEGER NOT NULL"),
    ("name_length_bytes", "INTEGER NOT NULL"),
    ("extension", "TEXT"),
    ("extensions_json", "TEXT NOT NULL"),
    ("stem_display", "TEXT"),
    ("is_hidden", "INTEGER NOT NULL"),
    ("entry_type", "TEXT NOT NULL"),
    ("is_regular", "INTEGER NOT NULL"),
    ("is_directory", "INTEGER NOT NULL"),
    ("is_symlink", "INTEGER NOT NULL"),
    ("is_fifo", "INTEGER NOT NULL"),
    ("is_socket", "INTEGER NOT NULL"),
    ("is_block_device", "INTEGER NOT NULL"),
    ("is_character_device", "INTEGER NOT NULL"),
    ("is_other", "INTEGER NOT NULL"),
    ("device_id", "TEXT"),
    ("device_major", "INTEGER"),
    ("device_minor", "INTEGER"),
    ("inode", "TEXT"),
    ("hardlink_key", "TEXT"),
    ("link_count", "INTEGER"),
    ("mode_int", "INTEGER"),
    ("mode_octal", "TEXT"),
    ("mode_symbolic", "TEXT"),
    ("permissions_octal", "TEXT"),
    ("uid", "INTEGER"),
    ("username", "TEXT"),
    ("gid", "INTEGER"),
    ("groupname", "TEXT"),
    ("size_bytes", "INTEGER"),
    ("allocated_bytes", "INTEGER"),
    ("blocks_512", "INTEGER"),
    ("io_block_size", "INTEGER"),
    ("is_sparse", "INTEGER"),
    ("sparse_ratio", "REAL"),
    ("sparse_extents_json", "TEXT"),
    ("physical_data_sha256", "TEXT"),
    ("physical_data_bytes", "INTEGER"),
    ("rdev", "TEXT"),
    ("rdev_major", "INTEGER"),
    ("rdev_minor", "INTEGER"),
    ("atime_ns", "TEXT"),
    ("mtime_ns", "TEXT"),
    ("ctime_ns", "TEXT"),
    ("birth_time_ns", "TEXT"),
    ("atime_iso", "TEXT"),
    ("mtime_iso", "TEXT"),
    ("ctime_iso", "TEXT"),
    ("birth_time_iso", "TEXT"),
    ("mtime_before_birth", "INTEGER"),
    ("atime_before_mtime", "INTEGER"),
    ("has_pre_epoch_time", "INTEGER"),
    ("has_future_time", "INTEGER"),
    ("filesystem_type", "TEXT"),
    ("mount_source", "TEXT"),
    ("mount_point_display", "TEXT"),
    ("mount_options", "TEXT"),
    ("statvfs_block_size", "INTEGER"),
    ("statvfs_fragment_size", "INTEGER"),
    ("statvfs_blocks", "INTEGER"),
    ("statvfs_blocks_free", "INTEGER"),
    ("statvfs_blocks_available", "INTEGER"),
    ("statvfs_files", "INTEGER"),
    ("statvfs_files_free", "INTEGER"),
    ("statvfs_files_available", "INTEGER"),
    ("statvfs_name_max", "INTEGER"),
    ("filesystem_flags_int", "INTEGER"),
    ("filesystem_flags_json", "TEXT"),
    ("xattr_count", "INTEGER NOT NULL"),
    ("xattr_names_json", "TEXT NOT NULL"),
    ("xattrs_b64_json", "TEXT NOT NULL"),
    ("acl_access_present", "INTEGER NOT NULL"),
    ("acl_default_present", "INTEGER NOT NULL"),
    ("acl_text", "TEXT"),
    ("symlink_target_display", "TEXT"),
    ("symlink_target_b64", "TEXT"),
    ("symlink_target_hex", "TEXT"),
    ("symlink_target_is_absolute", "INTEGER"),
    ("symlink_target_exists", "INTEGER"),
    ("symlink_target_type", "TEXT"),
    ("symlink_resolves_outside_root", "INTEGER"),
    ("extension_mime_type", "TEXT"),
    ("magic_description", "TEXT"),
    ("magic_mime_type", "TEXT"),
    ("magic_mime_encoding", "TEXT"),
    ("hash_algorithm", "TEXT"),
    ("content_sha256", "TEXT"),
    ("hash_status", "TEXT"),
    ("hash_bytes_read", "INTEGER"),
    ("head_sha256", "TEXT"),
    ("tail_sha256", "TEXT"),
    ("embedded_metadata_status", "TEXT"),
    ("embedded_metadata_json", "TEXT"),
    ("metadata_extraction_status", "TEXT"),
    ("metadata_parser_attempts_json", "TEXT"),
    ("raw_metadata_json", "TEXT"),
    ("raw_metadata_source_count", "INTEGER"),
    ("exiftool_status", "TEXT"),
    ("exiftool_metadata_json", "TEXT"),
    ("exiftool_error", "TEXT"),
    ("archive_metadata_json", "TEXT"),
    ("archive_error", "TEXT"),
    ("database_metadata_json", "TEXT"),
    ("database_error", "TEXT"),
    ("message_metadata_json", "TEXT"),
    ("message_error", "TEXT"),
    ("certificate_metadata_json", "TEXT"),
    ("certificate_error", "TEXT"),
    ("font_metadata_json", "TEXT"),
    ("font_error", "TEXT"),
    ("executable_metadata_json", "TEXT"),
    ("executable_error", "TEXT"),
    ("scientific_metadata_json", "TEXT"),
    ("scientific_error", "TEXT"),
    ("version_control_metadata_json", "TEXT"),
    ("version_control_error", "TEXT"),
    ("compressed_stream_metadata_json", "TEXT"),
    ("compressed_stream_error", "TEXT"),
    ("byte_structure_metadata_json", "TEXT"),
    ("byte_structure_error", "TEXT"),
    ("intentional_unsupported_metadata_json", "TEXT"),
    ("media_format_name", "TEXT"),
    ("media_duration_seconds", "REAL"),
    ("media_bit_rate", "INTEGER"),
    ("media_stream_count", "INTEGER"),
    ("media_tags_json", "TEXT"),
    ("pdf_title", "TEXT"),
    ("pdf_author", "TEXT"),
    ("pdf_subject", "TEXT"),
    ("pdf_keywords", "TEXT"),
    ("pdf_creator", "TEXT"),
    ("pdf_producer", "TEXT"),
    ("pdf_creation_date", "TEXT"),
    ("pdf_modification_date", "TEXT"),
    ("pdf_pages", "INTEGER"),
    ("pdf_encrypted", "TEXT"),
    ("pdf_page_size", "TEXT"),
    ("pdf_version", "TEXT"),
    ("image_format", "TEXT"),
    ("image_width", "INTEGER"),
    ("image_height", "INTEGER"),
    ("image_mode", "TEXT"),
    ("image_frame_count", "INTEGER"),
    ("image_exif_json", "TEXT"),
    ("office_title", "TEXT"),
    ("office_subject", "TEXT"),
    ("office_creator", "TEXT"),
    ("office_keywords", "TEXT"),
    ("office_description", "TEXT"),
    ("office_last_modified_by", "TEXT"),
    ("office_created", "TEXT"),
    ("office_modified", "TEXT"),
    ("office_revision", "TEXT"),
    ("office_category", "TEXT"),
    ("office_content_status", "TEXT"),
    ("office_language", "TEXT"),
    ("office_version", "TEXT"),
    ("scan_error", "TEXT"),
    ("stat_error", "TEXT"),
    ("metadata_error", "TEXT"),
    ("hash_error", "TEXT"),
    ("content_summary_short", "TEXT"),
    ("content_summary_long", "TEXT"),
    ("content_description", "TEXT"),
    ("content_keywords", "TEXT"),
    ("content_entities", "TEXT")
]

COLUMN_NAMES = [name for name, _ in COLUMN_DEFINITIONS]

CREATE_TABLE_SQL = (
    f"CREATE TABLE {TABLE_NAME} (\n  "
    + ",\n  ".join(f'"{name}" {definition}' for name, definition in COLUMN_DEFINITIONS)
    + "\n)"
)

INDEX_SQL = [
    f"CREATE UNIQUE INDEX idx_filesystem_entries_path ON {TABLE_NAME}(relative_path_b64)",
    f"CREATE INDEX idx_filesystem_entries_type ON {TABLE_NAME}(entry_type)",
    f"CREATE INDEX idx_filesystem_entries_inode ON {TABLE_NAME}(device_id, inode)",
    f"CREATE INDEX idx_filesystem_entries_hash ON {TABLE_NAME}(content_sha256)",
    f"CREATE INDEX idx_filesystem_entries_parent ON {TABLE_NAME}(parent_path_b64)",
]
