#!/usr/bin/env python3
from __future__ import annotations
import json, os, subprocess, sys, time, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGS = ROOT / "logs"
START = time.time()


def git_value(args: list[str], default: str = "unknown") -> str:
    try:
        return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True).strip()
    except Exception:
        try:
            return subprocess.check_output(["git", "-C", str(ROOT.parent), *args], text=True).strip()
        except Exception:
            return default


def run(cmd: list[str], timeout: int = 7200) -> dict:
    env = os.environ.copy()
    env.setdefault("DRT_DISABLE_CACHE", "1")
    env.setdefault("DRT_LLM_HOST", "127.0.0.1")
    env.setdefault("DRT_LLM_PORT", "14829")
    started = time.time()
    proc = subprocess.run(cmd, cwd=str(ROOT), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout, env=env)
    return {"cmd": cmd, "returncode": proc.returncode, "elapsed_seconds": round(time.time() - started, 3), "stdout_tail": proc.stdout[-8000:]}


def active_model() -> dict:
    endpoint = "http://127.0.0.1:14829"
    payload = {"endpoint": endpoint, "passed": False}
    try:
        with urllib.request.urlopen(endpoint + "/v1/models", timeout=5) as r:
            models = json.loads(r.read().decode())
        with urllib.request.urlopen(endpoint + "/slots", timeout=5) as r:
            slots = json.loads(r.read().decode())
        model = (models.get("data") or [{}])[0]
        model_id = model.get("id") or model.get("model") or model.get("name")
        ctx = slots[0].get("n_ctx") if isinstance(slots, list) and slots else None
        payload.update({"models": models, "slots": slots, "model_id": model_id, "model_meta": model.get("meta", {}), "runtime_context": ctx})
        payload["passed"] = "Qwen2.5-14B-Instruct-Q4_K_M" in str(model_id) and int(ctx or 0) >= 32768
    except Exception as exc:
        payload["error"] = str(exc)
    return payload


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def write_summary(payload: dict) -> None:
    LOGS.mkdir(exist_ok=True)
    (LOGS / "PHASE5_VALIDATION_SUMMARY.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = ["# Phase 5 Validation Summary", "", f"- status: `{'DONE' if payload.get('passed') else 'NOT DONE'}`", f"- elapsed_seconds: `{payload.get('elapsed_seconds')}`", "", "## Gates"]
    for k, v in payload["gates"].items():
        lines.append(f"- `{k}`: `{v}`")
    if payload.get("failures"):
        lines += ["", "## Failures"] + [f"- `{x}`" for x in payload["failures"]]
    (LOGS / "PHASE5_VALIDATION_SUMMARY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    readiness = ["# Final Phase 5 Readiness Report", "", f"- status: `{'READY' if payload.get('passed') else 'NOT READY'}`", "", "## Source"]
    readiness.append("- This report is generated from `logs/PHASE5_VALIDATION_SUMMARY.json` and the package verifier output.")
    readiness += ["", "## Gates"] + [f"- `{k}`: `{v}`" for k, v in payload["gates"].items()]
    (LOGS / "FINAL_PHASE5_READINESS_REPORT.md").write_text("\n".join(readiness) + "\n", encoding="utf-8")


def write_repo_package_state(package_zip: str | None = None, package_verifier_passed: bool | None = None) -> None:
    commit = git_value(["rev-parse", "HEAD"])
    branch = git_value(["rev-parse", "--abbrev-ref", "HEAD"])
    status = git_value(["status", "--short"], default="")
    payload = {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "current_commit": commit,
        "branch": branch,
        "git_status": status,
        "selected_active_package": package_zip,
        "package_verifier_passed": package_verifier_passed,
        "conclusion": "VALID_PACKAGE_FOUND" if package_zip and package_verifier_passed else "PACKAGE_PENDING_VERIFICATION",
        "note": "Generated by verify_phase5_complete.py so package manifest and repo-state commit agree.",
    }
    (LOGS / "PHASE5_REPO_AND_PACKAGE_STATE.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = [
        "# Phase 5 Repo And Package State",
        "",
        f"- timestamp: `{payload['timestamp']}`",
        f"- current_commit: `{commit}`",
        f"- branch: `{branch}`",
        f"- selected_active_package: `{package_zip}`",
        f"- package_verifier_passed: `{package_verifier_passed}`",
        f"- conclusion: `{payload['conclusion']}`",
        "",
        "## Git Status",
        "```",
        status[:12000],
        "```",
    ]
    (LOGS / "PHASE5_REPO_AND_PACKAGE_STATE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    commands = []
    gates = {}
    failures = []
    model = active_model()
    gates["active_model_proof"] = bool(model.get("passed"))
    (LOGS / "PHASE5_ACTIVE_MODEL_PROOF.json").write_text(json.dumps(model, indent=2, ensure_ascii=False), encoding="utf-8")
    compile_cmd = [sys.executable, "-m", "py_compile", "contracts.py", "dspg.py", "extract.py", "merge.py", "dspg_store.py", "run_staged_tests.py", "scripts/dspg_ingest_folder.py", "scripts/dspg_query.py", "scripts/audit_no_overfit_phase4.py", "scripts/verify_phase4_complete.py", "scripts/verify_phase5_package.py", "scripts/package_phase5_results.py"]
    commands.append(run(compile_cmd, timeout=180))
    gates["compile_checks"] = commands[-1]["returncode"] == 0
    commands.append(run([sys.executable, "scripts/verify_phase4_complete.py"], timeout=9000))
    gates["phase4_verifier_rerun"] = commands[-1]["returncode"] == 0
    phase4 = load_json(LOGS / "PHASE4_VERIFIER_RESULT.json")
    phase4_gates = phase4.get("gates", {})
    gates.update({
        "persistent_db_layer": bool(phase4_gates.get("database_backend_valid")),
        "blackbox_ingestion_query": bool(phase4_gates.get("all_model_blackbox_exact") and phase4_gates.get("all_model_source_grounded")),
        "strict_no_overfit_audit": bool(phase4_gates.get("phase4_no_overfit_audit_passed")),
        "all_ablation_variants": bool(phase4_gates.get("all_required_ablation_variants_present")),
        "component_only_wins": bool(phase4_gates.get("component_only_wins_proven")),
        "category_wins": bool(phase4_gates.get("category_wins_proven")),
        "context_propagation_no_leakage": bool(phase4_gates.get("context_carriers_stored") and phase4_gates.get("context_assignments_stored") and phase4_gates.get("date_time_type_separation") and phase4_gates.get("table_context_inheritance") and phase4_gates.get("context_no_leakage")),
        "herb_raw_probe_genuine_nonzero": bool(phase4_gates.get("herb_raw_probe_genuine_nonzero")),
        "folder_ingestion_stress": bool(phase4_gates.get("folder_ingestion_stress")),
        "phase4_package_ready_for_phase5": bool(phase4.get("passed")),
    })
    commands.append(run([sys.executable, "scripts/build_herb_raw_artifact_probe.py"], timeout=420))
    herb = load_json(LOGS / "HERB_RAW_ARTIFACT_PROBE_PHASE5.json")
    gates["herb_raw_artifact_phase5_report"] = commands[-1]["returncode"] == 0 and int(herb.get("accepted_raw_artifact_count", 0)) > 0
    # Write a pre-package summary so the package contains Phase 5 validation artifacts.
    pre_failures = [gate for gate, ok in gates.items() if not ok]
    pre_payload = {
        "status": "PACKAGING_PENDING" if not pre_failures else "NOT DONE",
        "passed": False,
        "start_time": START,
        "end_time": time.time(),
        "elapsed_seconds": round(time.time() - START, 3),
        "gates": {**gates, "package_generated": False, "package_verifier": False},
        "failures": pre_failures + ["package_generated", "package_verifier"],
        "active_model": model,
        "phase4_verifier": {"status": phase4.get("status"), "passed": phase4.get("passed"), "failures": phase4.get("failures")},
        "herb_raw_artifact_probe": {"accepted_raw_artifact_count": herb.get("accepted_raw_artifact_count")},
        "package_zip": None,
        "package_verification": {},
        "commands": commands,
    }
    write_summary(pre_payload)
    write_repo_package_state(package_zip=None, package_verifier_passed=False)
    commands.append(run([sys.executable, "scripts/package_phase5_results.py"], timeout=900))
    gates["package_generated"] = commands[-1]["returncode"] == 0
    package_manifest = load_json(LOGS / "PHASE5_PACKAGE_MANIFEST.json")
    package_zip = package_manifest.get("zip")
    verify_cmd = [sys.executable, "scripts/verify_phase5_package.py"] + ([package_zip] if package_zip else [])
    commands.append(run(verify_cmd, timeout=300))
    package_verify = load_json(LOGS / "PHASE5_PACKAGE_VERIFICATION.json")
    gates["package_verifier"] = commands[-1]["returncode"] == 0 and bool(package_verify.get("passed"))
    write_repo_package_state(package_zip=package_zip, package_verifier_passed=gates["package_verifier"])
    for gate, ok in gates.items():
        if not ok:
            failures.append(gate)
    payload = {
        "status": "DONE" if not failures else "NOT DONE",
        "passed": not failures,
        "start_time": START,
        "end_time": time.time(),
        "elapsed_seconds": round(time.time() - START, 3),
        "gates": gates,
        "failures": failures,
        "active_model": model,
        "phase4_verifier": {"status": phase4.get("status"), "passed": phase4.get("passed"), "failures": phase4.get("failures")},
        "herb_raw_artifact_probe": {"accepted_raw_artifact_count": herb.get("accepted_raw_artifact_count")},
        "package_zip": package_zip,
        "package_verification": {"passed": package_verify.get("passed"), "missing": package_verify.get("missing"), "errors": package_verify.get("errors")},
        "commands": commands,
    }
    write_summary(payload)
    print(json.dumps({"status": payload["status"], "passed": payload["passed"], "failures": failures, "package_zip": package_zip}, indent=2))
    return 0 if payload["passed"] else 1

if __name__ == "__main__":
    raise SystemExit(main())
